model:
  arch: minigpt_v2
  model_type: pretrain
  max_txt_len: 500
  end_sym: "</s>"
  low_resource: False
  prompt_template: '[INST] {} [/INST]'
  llama_model: "/home/user/project/MER-MCE/checkpoints/Llama-2-7b-chat-hf"
  ckpt: "/home/user/project/MER-MCE/checkpoints/save_checkpoint/20240127190_ECAC-cause/checkpoint_6.pth"
  lora_r: 64
  lora_alpha: 16


datasets:    
  ECAC_emotion_caption:  #
    batch_size: 1
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 30

evaluation_datasets:
  ECAC_emotion_caption:
    # eval_file_path: /home/user/selected_face/ECAC/test_window12.json # ECAC emotion
    # eval_file_path: /home/user/selected_face/ECAC/cause_test_window12_none.json # ECAV cause: test
    eval_file_path: results/submit_now-n_w-e.json # ECAV cause: submit

    img_path: /home/user/selected_face/ECAC/videos    
    max_new_tokens: 20
    batch_size: 20

run:
  task: image_text_pretrain
  name: minigptv2_evaluation
  save_path: /home/user/project/MER-MCE/results
